# Generated by Django 3.2 on 2021-06-17 06:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='uploads')),
                ('price', models.IntegerField(default=0, null=True)),
                ('dprice', models.FloatField(blank=True, default=0, null=True)),
                ('desc', models.CharField(default='', max_length=200, null=True)),
                ('Form_Factor', models.CharField(choices=[('Mini ATX', 'Mini ATX'), ('Micro ATX', 'Micro ATX'), ('ATX', 'ATX'), ('E-ATX', 'E-ATX')], default='Micro ATX', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('mobo', 'mobo'), ('ram', 'ram'), ('processor', 'processor'), ('graphicCard', 'graphic-card'), ('storage', 'storage'), ('powersupply', 'powersupply'), ('case', 'case')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='chipset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_chipset', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads')),
                ('cpu_name', models.CharField(max_length=250)),
                ('cpu_price', models.IntegerField(default=0)),
                ('dprice', models.FloatField(blank=True, default=0, null=True)),
                ('desc', models.TextField(default='', null=True)),
                ('generation', models.CharField(max_length=250)),
                ('category', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('chipset', models.ManyToManyField(to='shop.chipset')),
            ],
        ),
        migrations.CreateModel(
            name='Display_ports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(choices=[('HDMI', 'HDMI'), ('VGA', 'VGA'), ('DVI', 'DVI'), ('DISPLAY', 'DISPLAY')], default='HDMI', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Graphic_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='uploads')),
                ('Memory', models.CharField(choices=[('2GB', '2GB'), ('4GB', '4GB'), ('8GB', '8GB')], default='2GB', max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('dprice', models.FloatField(blank=True, default=0, null=True)),
                ('desc', models.TextField(default='', null=True)),
                ('version', models.CharField(choices=[('version 1', 'version 1'), ('version 2', 'version 2'), ('version 3', 'version 3')], default='version 1', max_length=250)),
                ('recommended_watt', models.CharField(default='', max_length=250)),
                ('category', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('dis_ports', models.ManyToManyField(to='shop.Display_ports')),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobo_name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='uploads')),
                ('price', models.IntegerField(default=0)),
                ('dprice', models.FloatField(blank=True, default=0, null=True)),
                ('desc', models.TextField(default='', null=True)),
                ('DIMM_sockets', models.CharField(choices=[('dual', 'dual'), ('single', 'single'), ('4', '4'), ('8', '8')], default='single', max_length=250)),
                ('Supported_ram', models.CharField(choices=[('ddr2', 'ddr2'), ('ddr3', 'ddr3'), ('ddr4', 'ddr4')], default='ddr3', max_length=250)),
                ('max_mhz', models.CharField(max_length=250)),
                ('Form_Factor', models.CharField(choices=[('Mini ATX', 'Mini ATX'), ('Micro ATX', 'Micro ATX'), ('ATX', 'ATX'), ('E-ATX', 'E-ATX')], default='Micro ATX', max_length=250)),
                ('Onboard_Graphics', models.CharField(blank=True, max_length=250, null=True)),
                ('Expensions_socket_version', models.CharField(choices=[('version 1', 'version 1'), ('version 2', 'version 2'), ('version 3', 'version 3'), ('version 4', 'version 4')], default='version 1', max_length=250)),
                ('Audio', models.CharField(blank=True, max_length=250, null=True)),
                ('LAN', models.CharField(blank=True, max_length=250, null=True)),
                ('USB', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('dprice', models.FloatField(blank=True, default=0, null=True)),
                ('desc', models.TextField(default='')),
                ('prating', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(upload_to='products')),
                ('case_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.case')),
                ('category', models.ForeignKey(blank=True, choices=[('mobo', 'mobo'), ('ram', 'ram'), ('processor', 'processor'), ('graphicCard', 'graphic-card'), ('storage', 'storage'), ('powersupply', 'powersupply'), ('case', 'case')], default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('cpu_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cpu')),
                ('graphic_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.graphic_card')),
                ('mobo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.motherboard')),
            ],
        ),
        migrations.CreateModel(
            name='socket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Wish_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendorx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=50, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'female'), ('other', 'other')], max_length=50, null=True)),
                ('ShopNmae', models.CharField(max_length=100, null=True)),
                ('cnic', models.ImageField(blank='True', default='', null=True, upload_to='uploads')),
                ('age', models.PositiveIntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='uploads')),
                ('price', models.IntegerField(default=0)),
                ('dprice', models.FloatField(blank=True, default=0, null=True)),
                ('desc', models.TextField(default='', null=True)),
                ('storage_type', models.CharField(choices=[('SATA', 'SATA'), ('IDE', 'IDE'), ('M.2', 'M.2')], default='SATA', max_length=250)),
                ('memory', models.CharField(choices=[('500GB', '500GB'), ('1TB', '1TB'), ('2TB', '2TB'), ('2TB', '2TB'), ('5TB', '5TB')], default='500GB', max_length=250)),
                ('category', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Smps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads')),
                ('name', models.CharField(max_length=250)),
                ('watt', models.CharField(choices=[('250', '250'), ('400', '400'), ('450', '450'), ('500', '500'), ('600', '600'), ('750', '750'), ('800', '800'), ('1000', '1000')], default='250', max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('dprice', models.FloatField(blank=True, default=0, null=True)),
                ('desc', models.TextField(default='', null=True)),
                ('category', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev', models.CharField(max_length=50)),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('review_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads')),
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=0, null=True)),
                ('dprice', models.FloatField(blank=True, default=0, null=True)),
                ('desc', models.TextField(default='', null=True)),
                ('type', models.CharField(choices=[('ddr3', 'ddr3'), ('ddr4', 'ddr4')], default='ddr3', max_length=250)),
                ('mhz', models.CharField(choices=[('1600', '1600'), ('2400', '2400'), ('2600', '2600'), ('2800', '2800'), ('3200', '3200')], default='1600', max_length=250)),
                ('memory', models.CharField(max_length=250)),
                ('category', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='psu_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.smps'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.ram'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.storage'),
        ),
        migrations.CreateModel(
            name='orderplaced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('packed', 'Paceked'), ('on the way', 'on the way'), ('delivered', 'delivered'), ('cancel', 'cancel')], max_length=250, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18)])),
                ('city', models.CharField(default='', max_length=250, null=True)),
                ('zipcode', models.CharField(max_length=250, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('single', 'single'), ('married', 'married'), ('widow', 'widow'), ('seprated', 'seprated'), ('commited', 'commited')], default='single', max_length=20)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='female', max_length=20)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pic', models.ImageField(null=True, upload_to='uploads')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='motherboard',
            name='Storage_Interface',
            field=models.ManyToManyField(default='', to='shop.Storage'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='chipset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.chipset'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='socket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.socket'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.vendor'),
        ),
        migrations.AddField(
            model_name='graphic_card',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.vendor'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('zipcode', models.CharField(max_length=250)),
                ('Address1', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cpu',
            name='socket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.socket'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.vendor'),
        ),
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AddField(
            model_name='case',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.vendor'),
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='builds_guides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('introduction', tinymce.models.HTMLField()),
                ('note_on_price', tinymce.models.HTMLField()),
                ('cpu', tinymce.models.HTMLField()),
                ('mobo', tinymce.models.HTMLField()),
                ('memory', tinymce.models.HTMLField()),
                ('storage', tinymce.models.HTMLField()),
                ('gpu', tinymce.models.HTMLField()),
                ('case', tinymce.models.HTMLField()),
                ('psu', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank='True', default='', null=True, upload_to='uploads')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Build_PC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(max_length=250)),
                ('Mobo', models.CharField(max_length=250)),
                ('ram', models.CharField(max_length=250)),
                ('graphiccard', models.CharField(max_length=250)),
                ('storage', models.CharField(max_length=250)),
                ('power_supply', models.CharField(max_length=250)),
                ('image', models.ImageField(blank='True', default='', null=True, upload_to='uploads')),
                ('Chases', models.CharField(max_length=250)),
                ('vote_count', models.IntegerField(blank=True, default=0, null=True)),
                ('vote_average', models.FloatField(blank=True, default=0.0, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
