# Generated by Django 3.2 on 2021-05-01 03:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='chipset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_chipset', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Display_ports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(choices=[('HDMI', 'HDMI'), ('VGA', 'VGA'), ('DVI', 'DVI'), ('DISPLAY', 'DISPLAY')], default='HDMI', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('dprice', models.FloatField(blank=True, default=0, null=True)),
                ('desc', models.CharField(default='', max_length=200)),
                ('prating', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(upload_to='uploads/product/')),
                ('category', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='socket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/product/')),
                ('storage_type', models.CharField(choices=[('SATA', 'SATA'), ('IDE', 'IDE'), ('M.2', 'M.2')], default='SATA', max_length=250)),
                ('memory', models.CharField(choices=[('500GB', '500GB'), ('1TB', '1TB'), ('2TB', '2TB'), ('2TB', '2TB'), ('5TB', '5TB')], default='500GB', max_length=250)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev', models.CharField(max_length=50)),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('review_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/product/')),
                ('type', models.CharField(choices=[('ddr3', 'ddr3'), ('ddr4', 'ddr4')], default='ddr3', max_length=250)),
                ('mhz', models.CharField(choices=[('1600', '1600'), ('2400', '2400'), ('2600', '2600'), ('2800', '2800'), ('3200', '3200')], default='1600', max_length=250)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18)])),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('single', 'single'), ('married', 'married'), ('widow', 'widow'), ('seprated', 'seprated'), ('commited', 'commited')], default='single', max_length=20)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='female', max_length=20)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^0?[5-9]{1}\\d{9}$')])),
                ('description', models.TextField(blank=True, null=True)),
                ('pic', models.ImageField(null=True, upload_to='uploads/product/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobo_name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='uploads/product/')),
                ('DIMM_sockets', models.CharField(choices=[('dual', 'dual'), ('single', 'single'), ('4', '4')], default='single', max_length=250)),
                ('Supported_ram', models.CharField(choices=[('ddr3', 'ddr3'), ('ddr4', 'ddr4')], default='ddr3', max_length=250)),
                ('Onboard_Graphics', models.CharField(blank=True, max_length=250, null=True)),
                ('Expensions_socket_version', models.CharField(choices=[('version 1', 'version 1'), ('version 2', 'version 2'), ('version 3', 'version 3')], default='version 1', max_length=250)),
                ('Audio', models.CharField(blank=True, max_length=250, null=True)),
                ('LAN', models.CharField(blank=True, max_length=250, null=True)),
                ('Storage_Interface', models.TextField(blank=True, max_length=250, null=True)),
                ('USB', models.TextField(blank=True, max_length=250, null=True)),
                ('chipset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.chipset')),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.socket')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Graphic_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/product/')),
                ('Memory', models.CharField(choices=[('2GB', '2GB'), ('4GB', '4GB'), ('8GB', '8GB')], default='2GB', max_length=250)),
                ('dis_ports', models.ManyToManyField(to='shop.Display_ports')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/product/')),
                ('cpu_name', models.CharField(max_length=250)),
                ('cpu_price', models.CharField(default='', max_length=250)),
                ('generation', models.CharField(max_length=250)),
                ('chipset', models.ManyToManyField(to='shop.chipset')),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.socket')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.vendor')),
            ],
        ),
    ]
