# Generated by Django 3.2 on 2021-05-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='max_mhz',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
