# Generated by Django 3.2 on 2021-05-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_motherboard_max_mhz'),
    ]

    operations = [
        migrations.AddField(
            model_name='ram',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='Supported_ram',
            field=models.CharField(choices=[('ddr2', 'ddr2'), ('ddr3', 'ddr3'), ('ddr4', 'ddr4')], default='ddr3', max_length=250),
        ),
    ]
