# Generated by Django 3.2 on 2021-05-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210501_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='ram',
            name='memory',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
