# Generated by Django 3.2 on 2021-05-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_graphic_card_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic_card',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
