# Generated by Django 3.2 on 2021-05-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_graphic_card_recommended_watt'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='Storage_Interface',
        ),
        migrations.AddField(
            model_name='motherboard',
            name='Storage_Interface',
            field=models.ManyToManyField(default='', to='shop.Storage'),
        ),
    ]
