# Generated by Django 3.2 on 2021-05-03 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210501_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('watt', models.CharField(choices=[('250', '250'), ('400', '400'), ('500', '500'), ('600', '600'), ('750', '750'), ('800', '800')], default='250', max_length=250)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.vendor')),
            ],
        ),
    ]
