# Generated by Django 3.2 on 2021-05-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_smps'),
    ]

    operations = [
        migrations.AddField(
            model_name='smps',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/product/'),
            preserve_default=False,
        ),
    ]
