# Generated by Django 3.2 on 2021-05-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_smps_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='Form_Factor',
            field=models.CharField(choices=[('Mini ATX', 'Mini ATX'), ('Micro ATX', 'Micro ATX'), ('ATX', 'ATX'), ('E-ATX', 'E-ATX')], default='Micro ATX', max_length=250),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='DIMM_sockets',
            field=models.CharField(choices=[('dual', 'dual'), ('single', 'single'), ('4', '4'), ('8', '8')], default='single', max_length=250),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='Expensions_socket_version',
            field=models.CharField(choices=[('version 1', 'version 1'), ('version 2', 'version 2'), ('version 3', 'version 3'), ('version 4', 'version 4')], default='version 1', max_length=250),
        ),
        migrations.AlterField(
            model_name='smps',
            name='watt',
            field=models.CharField(choices=[('250', '250'), ('400', '400'), ('450', '450'), ('500', '500'), ('600', '600'), ('750', '750'), ('800', '800'), ('1000', '1000')], default='250', max_length=250),
        ),
    ]
