# Generated by Django 3.2 on 2021-05-03 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210503_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='uploads/product/')),
                ('Form_Factor', models.CharField(choices=[('Mini ATX', 'Mini ATX'), ('Micro ATX', 'Micro ATX'), ('ATX', 'ATX'), ('E-ATX', 'E-ATX')], default='Micro ATX', max_length=250)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.vendor')),
            ],
        ),
    ]
