# Generated by Django 3.2 on 2021-05-03 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0012_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build_PC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(max_length=250)),
                ('Mobo', models.CharField(max_length=250)),
                ('ram', models.CharField(max_length=250)),
                ('graphiccard', models.CharField(max_length=250)),
                ('storage', models.CharField(max_length=250)),
                ('power_supply', models.CharField(max_length=250)),
                ('Chases', models.CharField(max_length=250)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
