# Generated by Django 3.2 on 2021-05-10 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0015_wish_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendorx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=50, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'female'), ('other', 'other')], max_length=50, null=True)),
                ('ShopNmae', models.CharField(max_length=100, null=True)),
                ('cnic', models.ImageField(blank='True', default='', null=True, upload_to='uploads/product/')),
                ('age', models.PositiveIntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
