# Generated by Django 3.2 on 2021-05-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20210512_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='zipcode',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
