# Generated by Django 3.2 on 2021-05-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_myprofile_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('inprogress', 'In-Progress'), ('completed', 'Completed')], max_length=250, null=True),
        ),
    ]
