# Generated by Django 3.2 on 2021-05-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('packed', 'Paceked'), ('on the way', 'on the way'), ('delivered', 'delivered'), ('cancel', 'cancel')], max_length=250, null=True),
        ),
    ]
