# Generated by Django 3.2 on 2021-05-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20210515_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='desc',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='dprice',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Form_Factor',
            field=models.CharField(choices=[('Mini ATX', 'Mini ATX'), ('Micro ATX', 'Micro ATX'), ('ATX', 'ATX'), ('E-ATX', 'E-ATX')], default='Micro ATX', max_length=250, null=True),
        ),
    ]
