# Generated by Django 3.2 on 2021-05-16 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20210515_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='case_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.case'),
        ),
    ]
