# Generated by Django 3.2 on 2021-05-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20210516_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='ram',
            name='desc',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='dprice',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
