# Generated by Django 3.2 on 2021-05-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20210516_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic_card',
            name='desc',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='graphic_card',
            name='dprice',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='graphic_card',
            name='price',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='desc',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='dprice',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='price',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='smps',
            name='desc',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='smps',
            name='dprice',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='smps',
            name='price',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='storage',
            name='desc',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='dprice',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='price',
            field=models.CharField(default='', max_length=250),
        ),
    ]
