# Generated by Django 3.2 on 2021-05-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_auto_20210516_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_price',
            field=models.IntegerField(default='', max_length=250),
        ),
    ]
