# Generated by Django 3.2 on 2021-05-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_auto_20210529_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic_card',
            name='price',
            field=models.IntegerField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='price',
            field=models.IntegerField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ram',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='smps',
            name='price',
            field=models.IntegerField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='storage',
            name='price',
            field=models.IntegerField(default='', max_length=250),
        ),
    ]
