# Generated by Django 3.2 on 2021-05-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_auto_20210529_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='desc',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='graphic_card',
            name='desc',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='desc',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ram',
            name='desc',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='smps',
            name='desc',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='desc',
            field=models.TextField(default='', null=True),
        ),
    ]
