# Generated by Django 3.2 on 2021-05-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_auto_20210529_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='cpu_price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='graphic_card',
            name='price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='smps',
            name='price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='storage',
            name='price',
            field=models.IntegerField(default=''),
        ),
    ]
