# Generated by Django 3.2 on 2021-05-29 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0038_auto_20210529_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='builds_guides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('introduction', models.TextField(blank=True)),
                ('note_on_price', models.TextField(blank=True)),
                ('cpu', models.TextField(blank=True)),
                ('mobo', models.TextField(blank=True)),
                ('memory', models.TextField(blank=True)),
                ('storage', models.TextField(blank=True)),
                ('gpu', models.TextField(blank=True)),
                ('case', models.TextField(blank=True)),
                ('psu', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
