# Generated by Django 3.2 on 2021-05-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_builds_guides'),
    ]

    operations = [
        migrations.AddField(
            model_name='builds_guides',
            name='image',
            field=models.ImageField(blank='True', default='', null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='build_pc',
            name='image',
            field=models.ImageField(blank='True', default='', null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='image',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='graphic_card',
            name='image',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='image',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='pic',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='image',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='smps',
            name='image',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='image',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='vendorx',
            name='cnic',
            field=models.ImageField(blank='True', default='', null=True, upload_to='uploads'),
        ),
    ]
