# Generated by Django 3.2 on 2021-05-30 01:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_auto_20210530_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builds_guides',
            name='case',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='builds_guides',
            name='cpu',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='builds_guides',
            name='gpu',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='builds_guides',
            name='introduction',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='builds_guides',
            name='memory',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='builds_guides',
            name='mobo',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='builds_guides',
            name='note_on_price',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='builds_guides',
            name='psu',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='builds_guides',
            name='storage',
            field=tinymce.models.HTMLField(),
        ),
    ]
